defmodule YoganHockeyWeb.PlayoffsLive do
  @moduledoc """
  LiveView for the NHL Playoffs predictions with AI-powered analysis.
  Mobile-first design optimized for iPhone usage.

  Predictions are fully autonomous - generated on deploy if missing,
  and automatically regenerated when games end.
  """
  use YoganHockeyWeb, :live_view

  alias YoganHockey.Playoffs
  alias YoganHockey.Playoffs.PredictionServer

  @impl true
  def mount(_params, _session, socket) do
    if connected?(socket) do
      Phoenix.PubSub.subscribe(YoganHockey.PubSub, "playoffs:updates")
    end

    # Check if generation is already in progress
    generating = connected?(socket) && PredictionServer.generating?()

    {:ok,
     socket
     |> assign(:page_title, "NHL Playoffs")
     |> assign(:active_tab, :picture)
     |> assign(:generating, generating)
     |> assign_async(:playoff_picture, fn -> load_playoff_picture() end)}
  end

  @impl true
  def handle_async(:playoff_picture, {:ok, %{playoff_picture: nil}}, socket) do
    # No predictions yet - PredictionServer will handle generation
    {:noreply, assign(socket, :playoff_picture, %Phoenix.LiveView.AsyncResult{ok?: true, result: nil})}
  end

  @impl true
  def handle_async(:playoff_picture, {:ok, %{playoff_picture: picture}}, socket) do
    {:noreply, assign(socket, :playoff_picture, %Phoenix.LiveView.AsyncResult{ok?: true, result: picture})}
  end

  @impl true
  def handle_async(:playoff_picture, {:exit, reason}, socket) do
    {:noreply, assign(socket, :playoff_picture, %Phoenix.LiveView.AsyncResult{failed: reason})}
  end

  # PubSub handlers for autonomous generation
  @impl true
  def handle_info({:generation_started}, socket) do
    {:noreply, assign(socket, :generating, true)}
  end

  @impl true
  def handle_info({:playoff_picture_updated, picture}, socket) do
    {:noreply,
     socket
     |> assign(:generating, false)
     |> assign(:playoff_picture, %Phoenix.LiveView.AsyncResult{ok?: true, result: picture})}
  end

  @impl true
  def handle_info({:generation_failed, _reason}, socket) do
    {:noreply,
     socket
     |> assign(:generating, false)
     |> put_flash(:error, "Failed to generate predictions. Will retry automatically.")}
  end

  @impl true
  def handle_info({:prediction_updated, _series_id, _prediction}, socket) do
    {:noreply, socket}
  end

  @impl true
  def handle_info({:bracket_updated, _bracket}, socket) do
    {:noreply, socket}
  end

  @impl true
  def handle_event("switch_tab", %{"tab" => tab}, socket) do
    {:noreply, assign(socket, :active_tab, String.to_atom(tab))}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div class="playoffs-container">
      <%!-- Header --%>
      <header class="playoffs-header">
        <h1>NHL Playoffs</h1>
        <p class="playoffs-subtitle">AI-Powered Predictions</p>
      </header>

      <%!-- Tab Navigation --%>
      <nav class="playoffs-tabs">
        <button
          class={"playoffs-tab #{if @active_tab == :picture, do: "active"}"}
          phx-click="switch_tab"
          phx-value-tab="picture"
        >
          Playoff Picture
        </button>
        <button
          class={"playoffs-tab #{if @active_tab == :bracket, do: "active"}"}
          phx-click="switch_tab"
          phx-value-tab="bracket"
        >
          Bracket
        </button>
      </nav>

      <%!-- Content --%>
      <div class="playoffs-content">
        <%= case @playoff_picture do %>
          <% %Phoenix.LiveView.AsyncResult{loading: true} -> %>
            <.loading_state />

          <% %Phoenix.LiveView.AsyncResult{ok?: true, result: nil} -> %>
            <.generating_state generating={@generating} />

          <% %Phoenix.LiveView.AsyncResult{ok?: true, result: picture} when not is_nil(picture) -> %>
            <%= if @active_tab == :picture do %>
              <.playoff_picture_view picture={picture} generating={@generating} />
            <% else %>
              <.bracket_view picture={picture} />
            <% end %>

          <% _ -> %>
            <.generating_state generating={@generating} />
        <% end %>
      </div>

      <%!-- Footer Info --%>
      <footer class="playoffs-footer">
        <p>Predictions generated by Claude AI. Auto-updates when games end.</p>
      </footer>
    </div>
    """
  end

  # --- Components ---

  defp loading_state(assigns) do
    ~H"""
    <div class="ai-generating-container">
      <div class="ai-brain-animation">
        <div class="brain-pulse"></div>
        <div class="brain-icon">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
            <path d="M12 2a9 9 0 0 1 9 9c0 3.074-1.676 5.59-3.442 7.395a20.36 20.36 0 0 1-2.876 2.416l-.682.46-.682-.46a20.354 20.354 0 0 1-2.876-2.416C8.676 16.59 7 14.074 7 11a5 5 0 0 1 10 0" />
            <circle cx="12" cy="11" r="3" />
          </svg>
        </div>
      </div>
      <h3 class="ai-generating-title">Loading Predictions</h3>
      <p class="ai-generating-text">Fetching playoff analysis...</p>
    </div>
    """
  end

  attr :generating, :boolean, default: false

  defp generating_state(assigns) do
    ~H"""
    <div class="ai-generating-container">
      <div class="ai-brain-animation">
        <div class="brain-pulse"></div>
        <div class="brain-rings">
          <div class="ring ring-1"></div>
          <div class="ring ring-2"></div>
          <div class="ring ring-3"></div>
        </div>
        <div class="brain-icon generating">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
            <path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96.44 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 1.98-3A2.5 2.5 0 0 1 9.5 2Z" />
            <path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96.44 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-1.98-3A2.5 2.5 0 0 0 14.5 2Z" />
          </svg>
        </div>
      </div>
      <h3 class="ai-generating-title">
        <%= if @generating do %>
          Analyzing NHL Standings
        <% else %>
          Preparing Analysis
        <% end %>
      </h3>
      <p class="ai-generating-text">
        <%= if @generating do %>
          Claude AI is evaluating team statistics, historical performance, and playoff dynamics...
        <% else %>
          Predictions will generate automatically
        <% end %>
      </p>
      <div class="ai-progress-dots">
        <span class="dot"></span>
        <span class="dot"></span>
        <span class="dot"></span>
      </div>
    </div>
    """
  end

  attr :picture, :map, required: true
  attr :generating, :boolean, default: false

  defp playoff_picture_view(assigns) do
    ~H"""
    <div class="playoff-picture">
      <%!-- Analysis Summary --%>
      <div class="analysis-card">
        <div class="analysis-header">
          <span class="ai-badge">AI Analysis</span>
          <span class="timestamp">
            {Calendar.strftime(@picture.generated_at, "%b %d, %H:%M")}
          </span>
        </div>
        <p class="analysis-text">{@picture.analysis}</p>
        <div class="cup-favorite">
          <span class="label">Cup Favorite:</span>
          <span class="value">{@picture.cup_favorite}</span>
        </div>
        <%= if @generating do %>
          <div class="regenerating-notice">
            <span class="spinner-small"></span>
            <span>Updating predictions...</span>
          </div>
        <% end %>
      </div>

      <%!-- Conference Cards --%>
      <.conference_card
        title="Eastern Conference"
        teams={@picture.eastern}
      />

      <.conference_card
        title="Western Conference"
        teams={@picture.western}
      />
    </div>
    """
  end

  attr :title, :string, required: true
  attr :teams, :list, required: true

  defp conference_card(assigns) do
    ~H"""
    <div class="conference-card">
      <h2 class="conference-title">{@title}</h2>

      <div class="teams-list">
        <%= for team <- @teams do %>
          <.team_prediction_card team={team} />
        <% end %>
      </div>
    </div>
    """
  end

  attr :team, :map, required: true

  defp team_prediction_card(assigns) do
    ~H"""
    <div class="team-pred-card">
      <div class="team-header">
        <div class="team-seed">#{@team.seed}</div>
        <div class="team-logo-container">
          <img :if={@team[:logo]} src={@team.logo} alt={@team.team_name} class="team-logo" />
          <span :if={!@team[:logo]} class="team-abbr">{@team[:abbreviation] || "?"}</span>
        </div>
        <div class="team-name-container">
          <span class="team-name">{@team.team_name}</span>
        </div>
      </div>

      <div class="prob-bars">
        <.prob_bar label="Playoffs" value={@team.playoff_prob} />
        <.prob_bar label="Round 2" value={@team.round2_prob} />
        <.prob_bar label="Conf Final" value={@team.conf_final_prob} />
        <.prob_bar label="Cup Final" value={@team.cup_final_prob} />
        <.prob_bar label="Win Cup" value={@team.cup_win_prob} highlight={true} />
      </div>
    </div>
    """
  end

  attr :label, :string, required: true
  attr :value, :float, required: true
  attr :highlight, :boolean, default: false

  defp prob_bar(assigns) do
    pct = round(assigns.value * 100)
    assigns = assign(assigns, pct: pct)

    ~H"""
    <div class={"prob-row #{if @highlight, do: "highlight"}"}>
      <span class="prob-label">{@label}</span>
      <div class="prob-bar-container">
        <div class="prob-bar-fill" style={"width: #{@pct}%"}></div>
      </div>
      <span class={"prob-value #{prob_color_class(@pct)}"}>{@pct}%</span>
    </div>
    """
  end

  attr :picture, :map, required: true

  defp bracket_view(assigns) do
    # Build matchups from predicted teams
    eastern = assigns.picture.eastern
    western = assigns.picture.western

    # Standard NHL bracket: 1v8, 2v7, 3v6, 4v5
    eastern_r1 = [
      build_matchup(Enum.at(eastern, 0), Enum.at(eastern, 7)),
      build_matchup(Enum.at(eastern, 1), Enum.at(eastern, 6)),
      build_matchup(Enum.at(eastern, 2), Enum.at(eastern, 5)),
      build_matchup(Enum.at(eastern, 3), Enum.at(eastern, 4))
    ]

    western_r1 = [
      build_matchup(Enum.at(western, 0), Enum.at(western, 7)),
      build_matchup(Enum.at(western, 1), Enum.at(western, 6)),
      build_matchup(Enum.at(western, 2), Enum.at(western, 5)),
      build_matchup(Enum.at(western, 3), Enum.at(western, 4))
    ]

    assigns =
      assigns
      |> assign(:eastern_r1, eastern_r1)
      |> assign(:western_r1, western_r1)

    ~H"""
    <div class="bracket-view">
      <%!-- Eastern Conference --%>
      <div class="bracket-conference">
        <h2 class="bracket-conf-title">Eastern Conference</h2>
        <div class="bracket-round">
          <h3 class="round-title">First Round</h3>
          <div class="bracket-matchups">
            <%= for matchup <- @eastern_r1 do %>
              <.matchup_card matchup={matchup} />
            <% end %>
          </div>
        </div>
      </div>

      <%!-- Western Conference --%>
      <div class="bracket-conference">
        <h2 class="bracket-conf-title">Western Conference</h2>
        <div class="bracket-round">
          <h3 class="round-title">First Round</h3>
          <div class="bracket-matchups">
            <%= for matchup <- @western_r1 do %>
              <.matchup_card matchup={matchup} />
            <% end %>
          </div>
        </div>
      </div>
    </div>
    """
  end

  defp build_matchup(team1, team2) when is_nil(team1) or is_nil(team2), do: nil

  defp build_matchup(team1, team2) do
    # Calculate relative win probability
    total_round2 = team1.round2_prob + team2.round2_prob
    team1_win = if total_round2 > 0, do: team1.round2_prob / total_round2, else: 0.5
    team2_win = 1 - team1_win

    %{
      team1: team1,
      team2: team2,
      team1_win_prob: team1_win,
      team2_win_prob: team2_win
    }
  end

  attr :matchup, :map, required: true

  defp matchup_card(assigns) do
    ~H"""
    <div :if={@matchup} class="matchup-card">
      <.matchup_team team={@matchup.team1} win_prob={@matchup.team1_win_prob} position="top" />
      <div class="matchup-divider">
        <span class="vs-badge">VS</span>
      </div>
      <.matchup_team team={@matchup.team2} win_prob={@matchup.team2_win_prob} position="bottom" />
    </div>
    """
  end

  attr :team, :map, required: true
  attr :win_prob, :float, required: true
  attr :position, :string, required: true

  defp matchup_team(assigns) do
    pct = round(assigns.win_prob * 100)
    assigns = assign(assigns, pct: pct)

    ~H"""
    <div class={"matchup-team #{@position}"}>
      <div class="matchup-team-info">
        <img :if={@team[:logo]} src={@team.logo} alt={@team.team_name} class="matchup-logo" />
        <div class="matchup-team-details">
          <span class="matchup-seed">(#{@team.seed})</span>
          <span class="matchup-name">{@team[:abbreviation] || @team.team_name}</span>
        </div>
      </div>
      <div class="matchup-prob-container">
        <div class="matchup-prob-bar">
          <div class={"matchup-prob-fill #{prob_color_class(@pct)}"} style={"width: #{@pct}%"}></div>
        </div>
        <span class={"matchup-prob-value #{prob_color_class(@pct)}"}>{@pct}%</span>
      </div>
    </div>
    """
  end

  # Helper functions

  defp prob_color_class(pct) when pct >= 70, do: "high"
  defp prob_color_class(pct) when pct >= 50, do: "medium"
  defp prob_color_class(_), do: "low"

  defp load_playoff_picture do
    case Playoffs.get_playoff_picture() do
      {:ok, picture} -> {:ok, %{playoff_picture: picture}}
      {:error, _reason} -> {:ok, %{playoff_picture: nil}}
    end
  end
end
